### ISSUE TITLE
Showing deleted resources

### ISSUE THREAD

**Issue by vierkantemeter** [Mark-H/getRelated#18]
I'm using the following snippet call:

[[getRelated? &parents=`3,6` &fields=`tv.tags:10,pagetitle:5,tv.categorieen:2` &returnFields=`pagetitle` &returnTVs=`hoofdafbeelding,hoofdafbeeldingAlt` &hideContainers=`1` &limit=`4` &tplOuter=`getrelated.article.outertpl` &tplRow=`getrelated.article.rowtpl` &noResults=`Er zijn nog geen gerelateerde pagina's.` &exclude=`1,2,11,21,25` &includeDeleted=`false`]]
`]]

However, deleted resources are also shown in the results. Am I missing something or is it a bug? Thanks!

**Comment by Mark-H** [comment]
Try removing the &includeDeleted property (it defaults to being off), or setting its value to 0 instead

**Comment by vierkantemeter** [comment]
Hmmm wait a minute... I'm doing something stupid here. It was working after all, without adding includeDeleted. SORRY!
